name: Run Terms of Service acceptance
description: Check if the user has previously accepted the Terms of Service, and prompt the user to accept if not

inputs:
  tos-location:
    description: 'Terms of Service location as an URL (https://foo.com/tos.html) or a Github repository file (/<owner>/<repo>/blob/<branch>/tos.html)'
    required: true
  pr-number:
    description: 'pull-request number'
    required: true
  pr-comment-tos-acceptance-missing:
    description: 'pull-request comment added when Terms of Service are not accepted ({0} in the value will be replaced by tos-location input)'
    required: true
  pr-comment-tos-acceptance-request:
    description: 'pull-request comment to accept the Terms of Service'
    required: true
  pr-comment-tos-acceptance-validation:
    description: 'pull-request comment added when Terms of Service are accepted'
    required: true
  signature-branch:
    description: 'Git branch where the signature file will be stored'
    required: true
  signature-location:
    description: 'Signature file location'
    required: true
  white-list:
    description: 'CSV List of users not required to accept the Terms of Service'
    required: true
  github-token:
    description: 'The token used for Github API requests'
    default: ${{ github.token }}
    required: false

runs:
  using: 'composite'
  steps:
    - name: Run Terms of Service acceptance
#      uses: contributor-assistant/github-action@v2.3.0
      id: check
      uses: jprinet/check-terms-of-service@v1
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        custom-notsigned-prcomment: ${{ format(inputs.pr-comment-tos-acceptance-missing, inputs.tos-location )}}
        custom-pr-sign-comment: ${{ inputs.pr-comment-tos-acceptance-request }}
        custom-allsigned-prcomment: ${{ inputs.pr-comment-tos-acceptance-validation }}
        branch: ${{ inputs.signature-branch }}
        path-to-signatures: ${{ inputs.signature-location }}
        allowlist: ${{ inputs.white-list }}
        path-to-document: 'unused'
        lock-pullrequest-aftermerge: false
        pr-number: ${{ inputs.pr-number }}
