import * as github from '@actions/github'

import * as githubInternal from '../shared/github'

export async function commentPullRequestWithBuildScanLinks(prNumber: number, buildScanLinks: string[]): Promise<void> {
    if (buildScanLinks.length > 0) {
        let comment = `#### Explore the Build Scan(s):\n`
        for (const buildScanLink of buildScanLinks) {
            comment += `${buildScanLink}\n`
        }
        comment += `###### Generated by gradle/github-actions/maven-build-scan/publish`

        await githubInternal.getOctokit().rest.issues.createComment({
            owner: github.context.repo.owner,
            repo: github.context.repo.repo,
            issue_number: prNumber,
            body: comment
        })
    }
}
