name: Save Maven Build Scan
description: Save Maven Build Scan

runs:
  using: composite
  steps:
    - name: Dump pull-request number
      env:
        BUILD_SCAN_DIR: '~/.m2/.gradle-enterprise/build-scan-data/'
      run: |
        if [ -d ${{ env.BUILD_SCAN_DIR }} ]; then
          SCAN_DIR=$(find ${{ env.BUILD_SCAN_DIR }} -type f -name "scan.scan" -exec dirname {} \; -quit)
          echo "PR_NUMBER=${{ github.event.number }}" > ${SCAN_DIR}/pr-number.properties
        fi
      shell: bash
    - name: Upload Build Scan as workflow Artifact
      uses: actions/upload-artifact@v3
      with:
        name: 'maven-build-scan-data'
        path: '~/.m2/.gradle-enterprise/build-scan-data/'
        retention-days: 1
