name: npm Setup Action
description: Setup action to capture npm Build Scans
author: Gradle team

inputs:
  develocity-access-key:
    description: 'Develocity access key. Should be set to a secret containing the Develocity Access key'
    required: false
  develocity-token-expiry:
    description: 'Develocity short-lived access tokens expiry in hours (Default 2 hours)'
    required: false
  github-token:
    description: 'The token used for Github API requests'
    default: ${{ github.token }}
    required: false
  develocity-injection-enabled:
    description: 'Whether to enable or not Develocity npm agent injection'
    required: false
  develocity-url:
    description: 'Develocity server URL'
    required: false
  develocity-npm-agent-version:
    description: 'Develocity npm agent version'
    default: 'latest'
    required: false
  develocity-npm-agent-install-location:
    description: 'Develocity npm agent installation location'
    default: '~/.node_libraries'
    required: false
  develocity-allow-untrusted-server:
    description: 'Whether to allow communicating with untrusted server'
    required: false
  develocity-pacote-version:
    description: 'Version of pacote to use to install the Develocity npm build agent'
    default: '21.0.0'
    required: false

runs:
  using: node20
  main: ../dist/setup-npm/main/index.js
