name: Verify pull-request check
description: Verify pull-request check

inputs:
  workflow-job-name:
    description: 'Workflow job name to verify'
    required: true
  github-token:
    description: 'The token used for Github API requests'
    default: ${{ github.token }}
    required: false

runs:
  using: 'composite'
  steps:
    - name: Verify pull-request check
      uses: actions/github-script@v6
      env:
        sha: ${{ github.event.workflow_run.head_sha }}
      with:
        github-token: ${{ inputs.github-token }}
        result-encoding: string
        script: |
          // returns most recent check runs first by default
          const checkRuns = await github.paginate('GET /repos/${{ github.repository }}/commits/{ref}/check-runs', {
            ref: process.env.sha,
            per_page: 50
          });
          for await (const cr of checkRuns) {
            // check only last execution of the workflow
            console.log('Checking execution of ' + cr.name);
            if(cr.name == '${{ inputs.workflow-job-name }}') {
              console.log('Found execution of ${{ inputs.workflow-job-name }} at ' + cr.completed_at);
              if(cr.conclusion == 'success') {
                return;
              } else {
                throw new Error('Found failed execution of ${{ inputs.workflow-job-name }} at ' + cr.completed_at);
              }
            }
          }
          throw new Error('No execution found for ${{ inputs.workflow-job-name }}');
