name: Publish Maven Build Scans
description: Publish Maven Build Scans

inputs:
  gradle-enterprise-url:
    description: 'Gradle Enterprise URL'
    required: true
  gradle-enterprise-access-key:
    description: 'Gradle Enterprise access key'
    required: false
  gradle-enterprise-extension-version:
    description: 'Gradle Enterprise extension version'
    required: true
  gradle-enterprise-allow-untrusted:
    description: 'Gradle Enterprise allow-untrusted flag'
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Download Build Scans
      uses: dawidd6/action-download-artifact@v2
      env:
        ARTIFACT_NAME: 'maven-build-scan-data'
      with:
        run_id: ${{ github.event.workflow_run.id }}
        name: ${{ env.ARTIFACT_NAME }}
        path: ${{ env.ARTIFACT_NAME }}
    - name: Restore Build Scans
      env:
        ARTIFACT_NAME: 'maven-build-scan-data'
        BUILD_SCAN_DIR: '~/.m2/.gradle-enterprise/build-scan-data/'
      run: |
        mkdir -p ${{ env.BUILD_SCAN_DIR }}
        cp -r ${{ env.ARTIFACT_NAME }}/* ${{ env.BUILD_SCAN_DIR }}
      shell: bash
    - name: Create Maven Project Structure
      env:
        PROJECT_DIR: 'maven-build-scan-publisher'
      run: |
        mkdir -p ${{ env.PROJECT_DIR }}/.mvn

        cat > ${{ env.PROJECT_DIR }}/pom.xml << EOF
        <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
          <modelVersion>4.0.0</modelVersion>
          <groupId>com.gradle</groupId>
          <artifactId>${{ env.PROJECT_DIR }}</artifactId>
          <version>1.0</version>
          <name>Maven Build Scan Publisher</name>
        </project>
        EOF

        cat > ${{ env.PROJECT_DIR }}/.mvn/extensions.xml << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <extensions>
          <extension>
            <groupId>com.gradle</groupId>
            <artifactId>gradle-enterprise-maven-extension</artifactId>
            <version>${{ inputs.gradle-enterprise-extension-version }}</version>
          </extension>
        </extensions>
        EOF

        cat > ${{ env.PROJECT_DIR }}/.mvn/gradle-enterprise.xml << EOF
        <?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
        <gradleEnterprise 
          xmlns="https://www.gradle.com/gradle-enterprise-maven" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://www.gradle.com/gradle-enterprise-maven https://www.gradle.com/schema/gradle-enterprise-maven.xsd">
          <server>
            <url>${{ inputs.gradle-enterprise-url }}</url>
            <allowUntrusted>${{ inputs.gradle-enterprise-allow-untrusted }}</allowUntrusted>
          </server>
        </gradleEnterprise>
        EOF
      shell: bash
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Publish build scan
      env:
        BUILD_SCAN_DIR: '~/.m2/.gradle-enterprise/build-scan-data/'
        GRADLE_ENTERPRISE_ACCESS_KEY: ${{ inputs.gradle-enterprise-access-key }}
        PROJECT_DIR: 'maven-build-scan-publisher'
      working-directory: ${{ env.PROJECT_DIR }}
      run: |
        set +e
        NB_SCANS=$(find ${{ env.BUILD_SCAN_DIR }}${{ inputs.gradle-enterprise-extension-version }} -type f -name "scan.scan"  | wc -l)
        for ((i=1; i <= $NB_SCANS; i++))
        do
          echo "BUILD SCAN PUBLICATION $i/$NB_SCANS"
          mvn gradle-enterprise:build-scan-publish-previous
        done
      shell: bash
