import * as output from '../../src/build-summary/dump'
import * as input from '../../src/utils/input'
import * as io from '../../src/utils/io'
import * as githubUtils from '../../src/utils/github'

const outputMock = jest.spyOn(output, 'dump')

describe('dump', () => {
    afterEach(() => {
        jest.clearAllMocks()
    })

    it('Dump triggers pull request comment and summary', async () => {

        const response = {
            data: [
                {
                    body: 'foo'
                },
                {
                    body: '###### Generated by gradle/github-actions/maven-build-scan-publish'
                }
            ]
        }
        const COMMENT_SIGNATURE = '###### Generated by gradle\/github-actions\/maven-build-scan-publish'
        //const regex = new RegExp(`/.*${COMMENT_SIGNATURE}.*/`)
        //const regex = new RegExp(`/.*maven.*/`, 'g')
        //const matchingComment = response.data.find(comment => comment && comment.body && comment.body.match(regex))
        const matchingComment = response.data.find(comment => comment && comment.body && comment.body.includes(COMMENT_SIGNATURE))

        // Given
        jest.spyOn(input, 'isSkipComment').mockReturnValue(false)
        jest.spyOn(input, 'isSkipSummary').mockReturnValue(false)
        const githubCommentMock = jest
            .spyOn(githubUtils, 'commentPullRequest')
            .mockReturnValue(Promise.resolve(undefined))
        const githubSummaryMock = jest
            .spyOn(githubUtils, 'addSummary')
            .mockReturnValue(Promise.resolve(undefined))
        const ioReadMock = jest.spyOn(io, 'readFileSync').mockReturnValue('foo=https://foo.bar/s/1234')
        const ioWriteMock = jest.spyOn(io, 'writeContentToFileSync').mockReturnValue()

        // when
        await output.dump({
            artifactId: 0,
            builds: [
                {jobName: 'foo', buildFailure: false, mavenGoals: 'clean package', workflowName: 'bar', buildId: 'foo', mavenVersion:'3.9'}
            ],
            prNumber: 42
        })

        // then
        expect(outputMock).toHaveReturned()
        expect(ioReadMock).toHaveBeenCalled()
        expect(githubCommentMock).toHaveBeenCalled()
        expect(githubSummaryMock).toHaveBeenCalled()
        expect(ioWriteMock).not.toHaveBeenCalled()
    })

    it('Dump with skip-comment dumps output to file', async () => {
        // Given
        jest.spyOn(input, 'isSkipComment').mockReturnValue(true)
        const githubCommentMock = jest
            .spyOn(githubUtils, 'commentPullRequest')
            .mockReturnValue(Promise.resolve(undefined))
        const ioReadMock = jest.spyOn(io, 'readFileSync').mockReturnValue('foo=https://foo.bar/s/1234')
        const ioWriteMock = jest.spyOn(io, 'writeContentToFileSync').mockReturnValue()

        // when
        await output.dump({
            artifactId: 0,
            builds: [
                {jobName: 'foo', buildFailure: false, mavenGoals: 'clean package', workflowName: 'bar', buildId: 'foo', mavenVersion:'3.9'}
            ],
            prNumber: 42
        })

        // then
        expect(outputMock).toHaveReturned()
        expect(ioReadMock).toHaveBeenCalled()
        expect(githubCommentMock).not.toHaveBeenCalled()
        expect(ioWriteMock).toHaveBeenCalled()
    })

    it('Dump with skip-summary does not add summary', async () => {
        // Given
        jest.spyOn(input, 'isSkipSummary').mockReturnValue(true)
        const githubSummaryMock = jest
            .spyOn(githubUtils, 'addSummary')
            .mockReturnValue(Promise.resolve(undefined))
        const ioReadMock = jest.spyOn(io, 'readFileSync').mockReturnValue('foo=https://foo.bar/s/1234')
        const ioWriteMock = jest.spyOn(io, 'writeContentToFileSync').mockReturnValue()

        // when
        await output.dump({
            artifactId: 0,
            builds: [
                {jobName: 'foo', buildFailure: false, mavenGoals: 'clean package', workflowName: 'bar', buildId: 'foo', mavenVersion:'3.9'}
            ],
            prNumber: 42
        })

        // then
        expect(outputMock).toHaveReturned()
        expect(ioReadMock).toHaveBeenCalled()
        expect(githubSummaryMock).not.toHaveBeenCalled()
        expect(ioWriteMock).toHaveBeenCalled()
    })

    it('Dump without build scan does nothing', async () => {
        // Given
        jest.spyOn(input, 'isSkipComment').mockReturnValue(false)
        const githubCommentMock = jest
            .spyOn(githubUtils, 'commentPullRequest')
            .mockReturnValue(Promise.resolve(undefined))
        const githubSummaryMock = jest
            .spyOn(githubUtils, 'addSummary')
            .mockReturnValue(Promise.resolve(undefined))
        const ioReadMock = jest.spyOn(io, 'readFileSync').mockReturnValue('foo=https://foo.bar/s/1234')
        const ioWriteMock = jest.spyOn(io, 'writeContentToFileSync').mockReturnValue()

        // when
        await output.dump({artifactId: 0, builds: [], prNumber: 42})

        // then
        expect(outputMock).toHaveReturned()
        expect(ioReadMock).toHaveBeenCalled()
        expect(githubCommentMock).not.toHaveBeenCalled()
        expect(githubSummaryMock).not.toHaveBeenCalled()
        expect(ioWriteMock).not.toHaveBeenCalled()
    })

    it('Dump with skip-comment and without build scan does nothing', async () => {
        // Given
        jest.spyOn(input, 'isSkipComment').mockReturnValue(false)
        const githubCommentMock = jest
            .spyOn(githubUtils, 'commentPullRequest')
            .mockReturnValue(Promise.resolve(undefined))
        const githubSummaryMock = jest
            .spyOn(githubUtils, 'addSummary')
            .mockReturnValue(Promise.resolve(undefined))
        const ioReadMock = jest.spyOn(io, 'readFileSync').mockReturnValue('foo=https://foo.bar/s/1234')
        const ioWriteMock = jest.spyOn(io, 'writeContentToFileSync').mockReturnValue()

        // when
        await output.dump({artifactId: 0, builds: [], prNumber: 42})

        // then
        expect(outputMock).toHaveReturned()
        expect(ioReadMock).toHaveBeenCalled()
        expect(githubCommentMock).not.toHaveBeenCalled()
        expect(githubSummaryMock).not.toHaveBeenCalled()
        expect(ioWriteMock).not.toHaveBeenCalled()
    })
})
