name: Publish Maven Build Scan
description: Publish Maven Build Scan

inputs:
  build-workflow-filename:
    description: 'Filename of the workflow where the maven-build-scan/save action was triggered'
    required: true
  develocity-url:
    description: 'Develocity URL'
    required: true
  develocity-access-key:
    description: 'Develocity access key'
    required: false
  tos-location:
    description: 'Terms of Service location as an URL (https://foo.com/tos.html) or a Github repository file (/<owner>/<repo>/blob/<branch>/tos.html)'
    required: true
  develocity-allow-untrusted:
    description: 'Develocity allow-untrusted flag'
    default: 'false'
  pr-comment-tos-acceptance-missing:
    description: 'pull-request comment added when Terms of Service are not accepted ({0} in the value will be replaced by tos-location input)'
    default: 'Please accept [Develocity Terms of Service]({0}) to get your pull-request Build Scan published by commenting this pull-request with the following message:'
  pr-comment-tos-acceptance-request:
    description: 'pull-request comment to accept the Terms of Service'
    default: 'I have read Develocity Terms of Service and I hereby accept the Terms'
  pr-comment-tos-acceptance-validation:
    description: 'pull-request comment added when Terms of Service are accepted'
    default: 'All Contributors have accepted Develocity Terms of Service.'
  tos-acceptance-file-branch:
    description: 'Git branch where the Terms of Service acceptance file will be stored'
    default: ${{ github.event.repository.default_branch }}
  tos-acceptance-file:
    description: 'Terms of Service acceptance file location'
    default: '.github/develocity-tos.json'
  white-list:
    description: 'CSV List of users not required to accept the Terms of Service'
    default: ''
  github-token:
    description: 'The token used for Github API requests'
    default: ${{ github.token }}
    required: false

runs:
  using: composite
  steps:
    - name: Load data
      id: load
      uses: gradle/github-actions/maven-build-scan/load@v1.0
      with:
        build-workflow-filename: ${{ inputs.build-workflow-filename }}
        pr-comment-tos-acceptance-request: ${{ inputs.pr-comment-tos-acceptance-request }}
    - name: Verify Terms of Service acceptance
      uses: gradle/github-actions/terms-of-service-acceptance/run@v1.0
      with:
        tos-location: ${{ inputs.tos-location }}
        pr-number: ${{ steps.load.outputs.pr-number }}
        pr-comment-tos-acceptance-missing: ${{ inputs.pr-comment-tos-acceptance-missing }}
        pr-comment-tos-acceptance-request: ${{ inputs.pr-comment-tos-acceptance-request }}
        pr-comment-tos-acceptance-validation: ${{ inputs.pr-comment-tos-acceptance-validation }}
        tos-acceptance-file-branch: ${{ inputs.tos-acceptance-file-branch }}
        tos-acceptance-file: ${{ inputs.tos-acceptance-file }}
        white-list: ${{ inputs.white-list }}
        github-token: ${{ inputs.github-token }}
    - name: Publish Maven Build Scans
      uses: gradle/github-actions/maven-build-scan/publish@v1.0
      with:
        develocity-url: ${{ inputs.develocity-url }}
        develocity-access-key: ${{ inputs.develocity-access-key }}
        pr-number: ${{ steps.load.outputs.pr-number }}
        develocity-allow-untrusted: ${{ inputs.develocity-allow-untrusted }}
        github-token: ${{ inputs.github-token }}
