name: TEST - Run Terms of Service acceptance verification

on:
  pull_request:

jobs:
  run-terms-of-service-acceptance:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      actions: write
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Terms of Service acceptance
        uses: ./terms-of-service-acceptance/run
        with:
          tos-location: 'https://foo.bar/tos.html'
          white-list: '*'
