name: TEST - Gradle - Terms of Service approval verification

on:
  pull_request:

jobs:
  check-terms-of-service-approval:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      actions: write
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Gradle - Terms of Service approval verification
        uses: ./terms-of-service/verify
        with:
          tos-location: 'https://foo.bar/tos.html'
          white-list: '*'
