name: Save Maven Build Scan
description: Save Maven Build Scan

runs:
  using: composite
  steps:
    - name: Upload Build Scan as workflow Artifact
      uses: actions/upload-artifact@v3
      with:
        name: 'maven-build-scan-data'
        path: '~/.m2/.gradle-enterprise/build-scan-data/'
